/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivateHomeRootRouteImport } from './routes/_private/home-root'
import { Route as PrivateWWorkspaceIdRouteRouteImport } from './routes/_private/w.$workspaceId/route'
import { Route as PrivateWWorkspaceIdIndexRouteImport } from './routes/_private/w.$workspaceId/index'
import { Route as PrivateWWorkspaceIdConfigRouteImport } from './routes/_private/w.$workspaceId/config'
import { Route as PrivateWWorkspaceIdEventsIndexRouteImport } from './routes/_private/w.$workspaceId/events/index'
import { Route as PrivateWWorkspaceIdNavHomeRouteImport } from './routes/_private/w.$workspaceId/_nav.home'
import { Route as PrivateWWorkspaceIdStockNavIndexRouteImport } from './routes/_private/w.$workspaceId/stock/_nav.index'
import { Route as PrivateWWorkspaceIdOrdersNavIndexRouteImport } from './routes/_private/w.$workspaceId/orders/_nav.index'
import { Route as PrivateWWorkspaceIdNotificationsNavIndexRouteImport } from './routes/_private/w.$workspaceId/notifications/_nav.index'
import { Route as PrivateWWorkspaceIdEventsEEventIdRouteRouteImport } from './routes/_private/w.$workspaceId/events/e.$eventId/route'
import { Route as PrivateWWorkspaceIdEventsEEventIdIndexRouteImport } from './routes/_private/w.$workspaceId/events/e.$eventId/index'
import { Route as PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdRouteRouteImport } from './routes/_private/w.$workspaceId/events/e.$eventId/demands/d.$demandId/route'
import { Route as PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdIndexRouteImport } from './routes/_private/w.$workspaceId/events/e.$eventId/demands/d.$demandId/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateHomeRootRoute = PrivateHomeRootRouteImport.update({
  id: '/home-root',
  path: '/home-root',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateWWorkspaceIdRouteRoute =
  PrivateWWorkspaceIdRouteRouteImport.update({
    id: '/w/$workspaceId',
    path: '/w/$workspaceId',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateWWorkspaceIdIndexRoute =
  PrivateWWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateWWorkspaceIdRouteRoute,
  } as any)
const PrivateWWorkspaceIdConfigRoute =
  PrivateWWorkspaceIdConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => PrivateWWorkspaceIdRouteRoute,
  } as any)
const PrivateWWorkspaceIdEventsIndexRoute =
  PrivateWWorkspaceIdEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => PrivateWWorkspaceIdRouteRoute,
  } as any)
const PrivateWWorkspaceIdNavHomeRoute =
  PrivateWWorkspaceIdNavHomeRouteImport.update({
    id: '/_nav/home',
    path: '/home',
    getParentRoute: () => PrivateWWorkspaceIdRouteRoute,
  } as any)
const PrivateWWorkspaceIdStockNavIndexRoute =
  PrivateWWorkspaceIdStockNavIndexRouteImport.update({
    id: '/stock/_nav/',
    path: '/stock/',
    getParentRoute: () => PrivateWWorkspaceIdRouteRoute,
  } as any)
const PrivateWWorkspaceIdOrdersNavIndexRoute =
  PrivateWWorkspaceIdOrdersNavIndexRouteImport.update({
    id: '/orders/_nav/',
    path: '/orders/',
    getParentRoute: () => PrivateWWorkspaceIdRouteRoute,
  } as any)
const PrivateWWorkspaceIdNotificationsNavIndexRoute =
  PrivateWWorkspaceIdNotificationsNavIndexRouteImport.update({
    id: '/notifications/_nav/',
    path: '/notifications/',
    getParentRoute: () => PrivateWWorkspaceIdRouteRoute,
  } as any)
const PrivateWWorkspaceIdEventsEEventIdRouteRoute =
  PrivateWWorkspaceIdEventsEEventIdRouteRouteImport.update({
    id: '/events/e/$eventId',
    path: '/events/e/$eventId',
    getParentRoute: () => PrivateWWorkspaceIdRouteRoute,
  } as any)
const PrivateWWorkspaceIdEventsEEventIdIndexRoute =
  PrivateWWorkspaceIdEventsEEventIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateWWorkspaceIdEventsEEventIdRouteRoute,
  } as any)
const PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdRouteRoute =
  PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdRouteRouteImport.update({
    id: '/demands/d/$demandId',
    path: '/demands/d/$demandId',
    getParentRoute: () => PrivateWWorkspaceIdEventsEEventIdRouteRoute,
  } as any)
const PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdIndexRoute =
  PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/home-root': typeof PrivateHomeRootRoute
  '/w/$workspaceId': typeof PrivateWWorkspaceIdRouteRouteWithChildren
  '/w/$workspaceId/config': typeof PrivateWWorkspaceIdConfigRoute
  '/w/$workspaceId/': typeof PrivateWWorkspaceIdIndexRoute
  '/w/$workspaceId/home': typeof PrivateWWorkspaceIdNavHomeRoute
  '/w/$workspaceId/events': typeof PrivateWWorkspaceIdEventsIndexRoute
  '/w/$workspaceId/events/e/$eventId': typeof PrivateWWorkspaceIdEventsEEventIdRouteRouteWithChildren
  '/w/$workspaceId/notifications': typeof PrivateWWorkspaceIdNotificationsNavIndexRoute
  '/w/$workspaceId/orders': typeof PrivateWWorkspaceIdOrdersNavIndexRoute
  '/w/$workspaceId/stock': typeof PrivateWWorkspaceIdStockNavIndexRoute
  '/w/$workspaceId/events/e/$eventId/': typeof PrivateWWorkspaceIdEventsEEventIdIndexRoute
  '/w/$workspaceId/events/e/$eventId/demands/d/$demandId': typeof PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdRouteRouteWithChildren
  '/w/$workspaceId/events/e/$eventId/demands/d/$demandId/': typeof PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/home-root': typeof PrivateHomeRootRoute
  '/w/$workspaceId/config': typeof PrivateWWorkspaceIdConfigRoute
  '/w/$workspaceId': typeof PrivateWWorkspaceIdIndexRoute
  '/w/$workspaceId/home': typeof PrivateWWorkspaceIdNavHomeRoute
  '/w/$workspaceId/events': typeof PrivateWWorkspaceIdEventsIndexRoute
  '/w/$workspaceId/notifications': typeof PrivateWWorkspaceIdNotificationsNavIndexRoute
  '/w/$workspaceId/orders': typeof PrivateWWorkspaceIdOrdersNavIndexRoute
  '/w/$workspaceId/stock': typeof PrivateWWorkspaceIdStockNavIndexRoute
  '/w/$workspaceId/events/e/$eventId': typeof PrivateWWorkspaceIdEventsEEventIdIndexRoute
  '/w/$workspaceId/events/e/$eventId/demands/d/$demandId': typeof PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_private': typeof PrivateRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_private/home-root': typeof PrivateHomeRootRoute
  '/_private/w/$workspaceId': typeof PrivateWWorkspaceIdRouteRouteWithChildren
  '/_private/w/$workspaceId/config': typeof PrivateWWorkspaceIdConfigRoute
  '/_private/w/$workspaceId/': typeof PrivateWWorkspaceIdIndexRoute
  '/_private/w/$workspaceId/_nav/home': typeof PrivateWWorkspaceIdNavHomeRoute
  '/_private/w/$workspaceId/events/': typeof PrivateWWorkspaceIdEventsIndexRoute
  '/_private/w/$workspaceId/events/e/$eventId': typeof PrivateWWorkspaceIdEventsEEventIdRouteRouteWithChildren
  '/_private/w/$workspaceId/notifications/_nav/': typeof PrivateWWorkspaceIdNotificationsNavIndexRoute
  '/_private/w/$workspaceId/orders/_nav/': typeof PrivateWWorkspaceIdOrdersNavIndexRoute
  '/_private/w/$workspaceId/stock/_nav/': typeof PrivateWWorkspaceIdStockNavIndexRoute
  '/_private/w/$workspaceId/events/e/$eventId/': typeof PrivateWWorkspaceIdEventsEEventIdIndexRoute
  '/_private/w/$workspaceId/events/e/$eventId/demands/d/$demandId': typeof PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdRouteRouteWithChildren
  '/_private/w/$workspaceId/events/e/$eventId/demands/d/$demandId/': typeof PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/home-root'
    | '/w/$workspaceId'
    | '/w/$workspaceId/config'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/home'
    | '/w/$workspaceId/events'
    | '/w/$workspaceId/events/e/$eventId'
    | '/w/$workspaceId/notifications'
    | '/w/$workspaceId/orders'
    | '/w/$workspaceId/stock'
    | '/w/$workspaceId/events/e/$eventId/'
    | '/w/$workspaceId/events/e/$eventId/demands/d/$demandId'
    | '/w/$workspaceId/events/e/$eventId/demands/d/$demandId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/home-root'
    | '/w/$workspaceId/config'
    | '/w/$workspaceId'
    | '/w/$workspaceId/home'
    | '/w/$workspaceId/events'
    | '/w/$workspaceId/notifications'
    | '/w/$workspaceId/orders'
    | '/w/$workspaceId/stock'
    | '/w/$workspaceId/events/e/$eventId'
    | '/w/$workspaceId/events/e/$eventId/demands/d/$demandId'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/login'
    | '/_private/home-root'
    | '/_private/w/$workspaceId'
    | '/_private/w/$workspaceId/config'
    | '/_private/w/$workspaceId/'
    | '/_private/w/$workspaceId/_nav/home'
    | '/_private/w/$workspaceId/events/'
    | '/_private/w/$workspaceId/events/e/$eventId'
    | '/_private/w/$workspaceId/notifications/_nav/'
    | '/_private/w/$workspaceId/orders/_nav/'
    | '/_private/w/$workspaceId/stock/_nav/'
    | '/_private/w/$workspaceId/events/e/$eventId/'
    | '/_private/w/$workspaceId/events/e/$eventId/demands/d/$demandId'
    | '/_private/w/$workspaceId/events/e/$eventId/demands/d/$demandId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/home-root': {
      id: '/_private/home-root'
      path: '/home-root'
      fullPath: '/home-root'
      preLoaderRoute: typeof PrivateHomeRootRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/w/$workspaceId': {
      id: '/_private/w/$workspaceId'
      path: '/w/$workspaceId'
      fullPath: '/w/$workspaceId'
      preLoaderRoute: typeof PrivateWWorkspaceIdRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/w/$workspaceId/': {
      id: '/_private/w/$workspaceId/'
      path: '/'
      fullPath: '/w/$workspaceId/'
      preLoaderRoute: typeof PrivateWWorkspaceIdIndexRouteImport
      parentRoute: typeof PrivateWWorkspaceIdRouteRoute
    }
    '/_private/w/$workspaceId/config': {
      id: '/_private/w/$workspaceId/config'
      path: '/config'
      fullPath: '/w/$workspaceId/config'
      preLoaderRoute: typeof PrivateWWorkspaceIdConfigRouteImport
      parentRoute: typeof PrivateWWorkspaceIdRouteRoute
    }
    '/_private/w/$workspaceId/events/': {
      id: '/_private/w/$workspaceId/events/'
      path: '/events'
      fullPath: '/w/$workspaceId/events'
      preLoaderRoute: typeof PrivateWWorkspaceIdEventsIndexRouteImport
      parentRoute: typeof PrivateWWorkspaceIdRouteRoute
    }
    '/_private/w/$workspaceId/_nav/home': {
      id: '/_private/w/$workspaceId/_nav/home'
      path: '/home'
      fullPath: '/w/$workspaceId/home'
      preLoaderRoute: typeof PrivateWWorkspaceIdNavHomeRouteImport
      parentRoute: typeof PrivateWWorkspaceIdRouteRoute
    }
    '/_private/w/$workspaceId/stock/_nav/': {
      id: '/_private/w/$workspaceId/stock/_nav/'
      path: '/stock'
      fullPath: '/w/$workspaceId/stock'
      preLoaderRoute: typeof PrivateWWorkspaceIdStockNavIndexRouteImport
      parentRoute: typeof PrivateWWorkspaceIdRouteRoute
    }
    '/_private/w/$workspaceId/orders/_nav/': {
      id: '/_private/w/$workspaceId/orders/_nav/'
      path: '/orders'
      fullPath: '/w/$workspaceId/orders'
      preLoaderRoute: typeof PrivateWWorkspaceIdOrdersNavIndexRouteImport
      parentRoute: typeof PrivateWWorkspaceIdRouteRoute
    }
    '/_private/w/$workspaceId/notifications/_nav/': {
      id: '/_private/w/$workspaceId/notifications/_nav/'
      path: '/notifications'
      fullPath: '/w/$workspaceId/notifications'
      preLoaderRoute: typeof PrivateWWorkspaceIdNotificationsNavIndexRouteImport
      parentRoute: typeof PrivateWWorkspaceIdRouteRoute
    }
    '/_private/w/$workspaceId/events/e/$eventId': {
      id: '/_private/w/$workspaceId/events/e/$eventId'
      path: '/events/e/$eventId'
      fullPath: '/w/$workspaceId/events/e/$eventId'
      preLoaderRoute: typeof PrivateWWorkspaceIdEventsEEventIdRouteRouteImport
      parentRoute: typeof PrivateWWorkspaceIdRouteRoute
    }
    '/_private/w/$workspaceId/events/e/$eventId/': {
      id: '/_private/w/$workspaceId/events/e/$eventId/'
      path: '/'
      fullPath: '/w/$workspaceId/events/e/$eventId/'
      preLoaderRoute: typeof PrivateWWorkspaceIdEventsEEventIdIndexRouteImport
      parentRoute: typeof PrivateWWorkspaceIdEventsEEventIdRouteRoute
    }
    '/_private/w/$workspaceId/events/e/$eventId/demands/d/$demandId': {
      id: '/_private/w/$workspaceId/events/e/$eventId/demands/d/$demandId'
      path: '/demands/d/$demandId'
      fullPath: '/w/$workspaceId/events/e/$eventId/demands/d/$demandId'
      preLoaderRoute: typeof PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdRouteRouteImport
      parentRoute: typeof PrivateWWorkspaceIdEventsEEventIdRouteRoute
    }
    '/_private/w/$workspaceId/events/e/$eventId/demands/d/$demandId/': {
      id: '/_private/w/$workspaceId/events/e/$eventId/demands/d/$demandId/'
      path: '/'
      fullPath: '/w/$workspaceId/events/e/$eventId/demands/d/$demandId/'
      preLoaderRoute: typeof PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdIndexRouteImport
      parentRoute: typeof PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdRouteRoute
    }
  }
}

interface PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdRouteRouteChildren {
  PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdIndexRoute: typeof PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdIndexRoute
}

const PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdRouteRouteChildren: PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdRouteRouteChildren =
  {
    PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdIndexRoute:
      PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdIndexRoute,
  }

const PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdRouteRouteWithChildren =
  PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdRouteRoute._addFileChildren(
    PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdRouteRouteChildren,
  )

interface PrivateWWorkspaceIdEventsEEventIdRouteRouteChildren {
  PrivateWWorkspaceIdEventsEEventIdIndexRoute: typeof PrivateWWorkspaceIdEventsEEventIdIndexRoute
  PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdRouteRoute: typeof PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdRouteRouteWithChildren
}

const PrivateWWorkspaceIdEventsEEventIdRouteRouteChildren: PrivateWWorkspaceIdEventsEEventIdRouteRouteChildren =
  {
    PrivateWWorkspaceIdEventsEEventIdIndexRoute:
      PrivateWWorkspaceIdEventsEEventIdIndexRoute,
    PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdRouteRoute:
      PrivateWWorkspaceIdEventsEEventIdDemandsDDemandIdRouteRouteWithChildren,
  }

const PrivateWWorkspaceIdEventsEEventIdRouteRouteWithChildren =
  PrivateWWorkspaceIdEventsEEventIdRouteRoute._addFileChildren(
    PrivateWWorkspaceIdEventsEEventIdRouteRouteChildren,
  )

interface PrivateWWorkspaceIdRouteRouteChildren {
  PrivateWWorkspaceIdConfigRoute: typeof PrivateWWorkspaceIdConfigRoute
  PrivateWWorkspaceIdIndexRoute: typeof PrivateWWorkspaceIdIndexRoute
  PrivateWWorkspaceIdNavHomeRoute: typeof PrivateWWorkspaceIdNavHomeRoute
  PrivateWWorkspaceIdEventsIndexRoute: typeof PrivateWWorkspaceIdEventsIndexRoute
  PrivateWWorkspaceIdEventsEEventIdRouteRoute: typeof PrivateWWorkspaceIdEventsEEventIdRouteRouteWithChildren
  PrivateWWorkspaceIdNotificationsNavIndexRoute: typeof PrivateWWorkspaceIdNotificationsNavIndexRoute
  PrivateWWorkspaceIdOrdersNavIndexRoute: typeof PrivateWWorkspaceIdOrdersNavIndexRoute
  PrivateWWorkspaceIdStockNavIndexRoute: typeof PrivateWWorkspaceIdStockNavIndexRoute
}

const PrivateWWorkspaceIdRouteRouteChildren: PrivateWWorkspaceIdRouteRouteChildren =
  {
    PrivateWWorkspaceIdConfigRoute: PrivateWWorkspaceIdConfigRoute,
    PrivateWWorkspaceIdIndexRoute: PrivateWWorkspaceIdIndexRoute,
    PrivateWWorkspaceIdNavHomeRoute: PrivateWWorkspaceIdNavHomeRoute,
    PrivateWWorkspaceIdEventsIndexRoute: PrivateWWorkspaceIdEventsIndexRoute,
    PrivateWWorkspaceIdEventsEEventIdRouteRoute:
      PrivateWWorkspaceIdEventsEEventIdRouteRouteWithChildren,
    PrivateWWorkspaceIdNotificationsNavIndexRoute:
      PrivateWWorkspaceIdNotificationsNavIndexRoute,
    PrivateWWorkspaceIdOrdersNavIndexRoute:
      PrivateWWorkspaceIdOrdersNavIndexRoute,
    PrivateWWorkspaceIdStockNavIndexRoute:
      PrivateWWorkspaceIdStockNavIndexRoute,
  }

const PrivateWWorkspaceIdRouteRouteWithChildren =
  PrivateWWorkspaceIdRouteRoute._addFileChildren(
    PrivateWWorkspaceIdRouteRouteChildren,
  )

interface PrivateRouteRouteChildren {
  PrivateHomeRootRoute: typeof PrivateHomeRootRoute
  PrivateWWorkspaceIdRouteRoute: typeof PrivateWWorkspaceIdRouteRouteWithChildren
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateHomeRootRoute: PrivateHomeRootRoute,
  PrivateWWorkspaceIdRouteRoute: PrivateWWorkspaceIdRouteRouteWithChildren,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
